@CleanArchitecture.ApiService_HostAddress = https://localhost:7301

GET {{CleanArchitecture.ApiService_HostAddress}}/todoitems

###

POST {{CleanArchitecture.ApiService_HostAddress}}/todoitems
Content-Type: application/json

{
  "name":"walk dog",
  "isComplete":true
}

###

GET {{CleanArchitecture.ApiService_HostAddress}}/todoitems/complete

###

@id=1
DELETE {{CleanArchitecture.ApiService_HostAddress}}/todoitems/{{id}}

###

GET {{CleanArchitecture.ApiService_HostAddress}}/todoitems/{{id}}

###

PUT {{CleanArchitecture.ApiService_HostAddress}}/todoitems/{{id}}
Content-Type: application/json

{
  "name":"walk cat",
  "isComplete":false
}

###
